import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getMessages } from "next-intl/server";
import { routing } from "@/i18n/routing";
import NotFound from "./not-found";
import Header from "./components/Header";
import Footer from "./components/footer";
import { Providers } from "./client/queryClientProivder";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Herafy",
  description: "Generated by create next app",
  icons: {
    icon: "/1.11.svg",
  },
};

export default async function RootLayout({ params, children }) {
  const resolvedParams = await params;
  if (!hasLocale(routing.locales, resolvedParams.locale)) {
    return <NotFound />;
  }

  const messages = await getMessages();
  return (
    <html
      lang={resolvedParams.locale}
      dir={resolvedParams.locale === "ar" ? "rtl" : "ltr"}
    >
      <body>
        <NextIntlClientProvider
          locale={resolvedParams.locale}
          messages={messages}
        >
          <Providers>
            <Header />
            {children}
            <Footer />
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
