import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getMessages } from "next-intl/server";
import { routing } from "@/i18n/routing";
import NotFound from "./not-found";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ params, children }) {
  const resolvedParams = await params;
  if (!hasLocale(routing.locales, resolvedParams.locale)) {
    return <NotFound />;
  }

  const messages = await getMessages();
  return (
    <html
      lang={resolvedParams.locale}
      dir={resolvedParams.locale === "ar" ? "rtl" : "ltr"}
    >
      <body>
        <NextIntlClientProvider
          locale={resolvedParams.locale}
          messages={messages}
        >
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
